### ISSUE TITLE
IPTV SMARTERS

### ISSUE THREAD

**Issue by BRUCKAO** [Ramys/Iptv-Brasil-2023#51]
Televisão (preencha as seguintes informações):**
 - Dispositivo: LG
 - SO: IPTV SMARTERS PRO

Boa noite Grandioso, tudo certo ?

Gostaria de informar que utilizo o IPTV Smarters Pro na tv LG com o login 096154, porém na sessão LIVE TV o canais funcionam por um curto tempo de aproximadamente 30s a 1 minuto e depois para de funcionar, voltando apenas quando se troca o canal e funcionando também somente por esse tempo.

Sei que faz isso de forma voluntária, porém você nos pedem que informe caso não funcione.

Tem algum login que funciona normalmente ?

Muito obrigado pelo seu empenho

Tenha uma excelente noite ou dia (não sei qual o horário estará lendo)

Forte abraço.

**Comment by area189** [comment]
Fala Ramys , quanto tempo , belezinha?
Amigo , estou pesquisando sobre **OpenBullet** , manja puxar por lá?

**Comment by Ramys** [comment]
> Fala Ramys , quanto tempo , belezinha? Amigo , estou pesquisando sobre **OpenBullet** , manja puxar por lá?

e ai manin, firme!
Cara, não conheço...Vou estudar isso ai ein...se for pra ajudar geral , farei questão !

**Comment by BRUCKAO** [comment]
Mestre @Ramys sobre a situação de travas após alguns segundos no app IPTV Smarters Pro tanto no celular quanto na TV, o que poderia ser ? O usuário teste é: Login 096154.

Desde já agradeço seu empenho.

**Comment by Ramys** [comment]
Atualizado!
