### ISSUE TITLE
lista off

### ISSUE THREAD

**Issue by Etavares1301** [Ramys/Iptv-Brasil-2023#52]
boa tarde!
estava usando a lista http://axr.life:80, mas ela parou de funcionar. pode me ajudar?
tentei colocar a lista http://api.magiaiptv.com/ mas ela fica só carregando.

**Comment by Ramys** [comment]
Irei atualizar todas agora!

**Comment by Ramys** [comment]
Por favor vc poderia indicar as listas off? 
para a correção ser mais rápidas.

**Comment by ViniciusLuisZ** [comment]
A lista [a1xr.m3u8](https://github.com/Ramys/Iptv-Brasil-2023/blob/master/a1xr.m3u8) está offline

**Comment by Futura1976** [comment]
boa noite lista [http://acsb.sh:80] off

**Comment by Ramys** [comment]
Aproveita!
