### ISSUE TITLE
Atualiza a Lista

### ISSUE THREAD

**Issue by Pokye** [Ramys/Iptv-Brasil-2023#59]
Infelizmente a ultima lista atualizada em 6 de maio, está caindo muito, assito algo por alguns segundos e cai. provavelmente é muita gente já assistindo. coloca mais listas por favor <3

**Comment by Ramys** [comment]
Aopa!!
Testa essa.
https://github.com/Ramys/Iptv-Brasil-2023/blob/master/CanaisB5.m3u8
