### ISSUE TITLE
Bug ao usar o aplicativo na TV

### ISSUE THREAD

**Issue by matheussouzall** [Ramys/Iptv-Brasil-2023#61]
Ele descreve o usuário ou senha inválido quando tento usar o aplicativo na TV, celular ou mesmo no navegador do computador.

**Comment by Ramys** [comment]
Qual aplicativo você usa , e qual login e senha vc tem ultilizado?

**Comment by matheussouzall** [comment]
Aplicativo - IPTV Smarters Pro

Qualquer nome: Magiaiptv

Login: 800196

Senha: 128093

url: http://api.magiaiptv.com url2: http://api.magiaiptv.com:80
<http://api.magiaiptv.com/>
*Matheus Souza Freitas*
*Carazinho - RS*


Em ter., 27 de jun. de 2023 às 12:06, Ramys ***@***.***>
escreveu:

**Comment by matheussouzall** [comment]
Mesmo utilizando a senha de cima, do club tv não funciona no aplicativo
iptvmasters.


Como faço para acessar o app na tv?

*Matheus Souza Freitas*
*Carazinho - RS*


Em qua., 5 de jul. de 2023 às 12:06, Ramys ***@***.***>
escreveu:

**Comment by abelcrvg** [comment]
Para utilizar o do club tv você deve utilizar do seguinte modo

Login : bF3y9W
Senha: 68GSme
URL : http://acsb.sh:80
Ou: http://bdtb.io:80

**Comment by matheussouzall** [comment]
Deu certo. Obrigado.

Em qua., 19 de jul. de 2023 15:14, abelcrvg ***@***.***>
escreveu:

**Comment by matheussouzall** [comment]
Bom dia, tudo bem?

O aplicativo parou de funcionar. Tento acessar mas não carrega os canais.
Tento atualizar e ele diz dados incorretos.
Como posso proceder?

Abraços

Em qua., 26 de jul. de 2023 11:36, Matheus Souza <
***@***.***> escreveu:

**Comment by Ramys** [comment]
Qual aplicativo vc usa e qual lista vc usa tb?

**Comment by Ramys** [comment]
Abra um novo issues , assim eu posso te responder mais rápido..
Nesses fechados eu não visualizo.

**Comment by matheussouzall** [comment]
Consegui já. Muito obrigado.

Em seg., 11 de set. de 2023 14:07, Ramys ***@***.***>
escreveu:
