### ISSUE TITLE
Nenhum filme está reproduzindo

### ISSUE THREAD

**Issue by GeniShimada** [Ramys/Iptv-Brasil-2023#62]
**informa que este filme não pode ser reproduzido 
Aparece num texto bem em cima com letra azul
![image](https://github.com/Ramys/Iptv-Brasil-2023/assets/32342981/5ce83b42-2ac1-413a-aa79-9a9e427bbc50)

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.
![image](https://github.com/Ramys/Iptv-Brasil-2023/assets/32342981/7e7c57fd-ebb2-4f01-a41d-d21da9083afa)

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by GeniShimada** [comment]
Eu usava login senha e servidor
No aplicativo 
Mas expirou em 23/6

**Comment by Ramys** [comment]
Use esse login e senha.
Login: bF3y9W
Senha: 68GSme

**Comment by GeniShimada** [comment]
Obrigado pela resposta ramys

**Comment by Ramys** [comment]
Bom dia.
Segue o url e porta.

http://acsb.sh:80

**Comment by GeniShimada** [comment]
Obrigado
