### ISSUE TITLE
Web Player Iptv não está funcionando 

### ISSUE THREAD

**Issue by costagold** [Ramys/Iptv-Brasil-2023#63]
uso normalmente o aplicativo Iptv Smartes Player na Smart Tv, porém com o seguinte login:

Qualquer nome: Magiaiptv

Login: 800196

senha: 128093

Não consegui entrar na lista de canais.

**Comment by BRUCKAO** [comment]
Opa mestre .. esse da club tv não encontrei

**Comment by Ramys** [comment]
> Opa mestre .. esse da club tv não encontrei 

Login : bF3y9W 
Senha: 68GSme
Caso precise use o url: http://acsb.sh:80

**Comment by BRUCKAO** [comment]
> > Opa mestre .. esse da club tv não encontrei
> 
> Login : bF3y9W Senha: 68GSme Caso precise use o url: http://acsb.sh:80 Ou: http://bdtb.io:80

Testei aqui no IPTV Smarters PRO na TV e no Celular.
Canais funcionam, porém todos os canais que testei, após alguns segundos dá tela preta: "Sorry, this video can not be played. Please try again or pick another video."

Já na Aba "Movies" fui em ALL e pesquisei o filme "O PIOR VIZINHO DO MUNDO" e apareceu tela preta com 5 tentativas e Aba "Series" o mesmo aconteceu em Globoplay "OS OUTROS".

**Comment by Ramys** [comment]
> > > Opa mestre .. esse da club tv não encontrei
> > 
> > Login : bF3y9W Senha: 68GSme Caso precise use o url: http://acsb.sh:80 Ou: http://bdtb.io:80
> 
> Testei aqui no IPTV Smarters PRO na TV e no Celular.
> Canais funcionam, porém todos os canais que testei, após alguns segundos dá tela preta: "Sorry, this video can not be played. Please try again or pick another video."
> 
> Já na Aba "Movies" fui em ALL e pesquisei o filme "O PIOR VIZINHO DO MUNDO" , entre outros e apareceu tela preta com 5 tentativas e Aba "Series" o mesmo aconteceu em Globoplay "OS OUTROS" e entre outros.
> 
> Desde já agradeço por de forma gratuita está realizando esses reparos.

Na lista que passei?
Aqui tá tudo normal.
