### ISSUE TITLE
Alguma lista de filmes e séries?

### ISSUE THREAD

**Issue by Brunowilliang** [Ramys/Iptv-Brasil-2023#65]
estou criando uma aplicativo para estudos e estava precisando de uma lista m3u8 de filmes e séries, testei as que está no repositório mas nao está funcionando

**Comment by Ramys** [comment]
Bom dia..
Você precisa somente dos filmes e séries, ou todo o conteúdo?
Qual aplicativo você usa para reproduzir os mesmos?

**Comment by Brunowilliang** [comment]
Então, gostaria de entender melhor essas lista, usei a lista de TV que esta no repo e funcionou bem, mas trava bastante hahahaha, se vc tiver algum fornecedor dessas listas para me informar pq gostaria de criar um app para que nao ficasse travando...

e se tiver uma só de filmes e séries e uma só com TV seria perfeito.

**Comment by Ramys** [comment]
Você sabe editar a extensão em m3u8?
Teria que adicionar manualmente cada área..
Tipo:..
Primeira extensão só com série..
Segunda extensão só com filmes
E por fim terceira extensão só com canais..
O fato de travar muito é pq a lista de limita a uma quantidade mínima de ips.
Tenho outras que limita até uns 5 ips.
Posso lhe enviar editado e modifica somente de acordo como vc preferir.
Uma super dica...
Compre uma tv box , pois ela terá mais qualidade e tecnologia suficiente para instalar apk em modo Android..
Assim seria mais fácil para vc e até irá melhorar os travamentos, pois as TVs não tem toda essa melhoria que um aparelho voltado somente para uma plataforma.

**Comment by Brunowilliang** [comment]
Eu consigo editar ela sim tranquilo, o problema maior é os travamentos kkk
Eu estou desenvolvendo um aplicativo para iOS e Android, então a minha preocupação maior é realmente com eles.
Se puder compartilha por favor as listas de até 5 ips que qualquer coisa eu vou tentar fazer de alguma forma elas se alternarem para não travar.
Outra pergunta seria sobre essas listas, existe algum distribuidor que disponibiliza elas? se tiver e me puder passar eu agradeceria, sou meio leigo no assunto e é bem chato de achar alguma que funcione

**Comment by Ramys** [comment]
Você sabe editar a extensão em m3u8?
Teria que adicionar manualmente cada área..
Tipo:..
Primeira extensão só com série..
Segunda extensão só com filmes
E por fim terceira extensão só com canais..
O fato de travar muito é pq a lista de limita a uma quantidade mínima de ips.
Tenho outras que limita até uns 5 ips.
Posso lhe enviar editado e modifica somente de acordo como vc preferir.
Uma super dica...
Compre uma tv box , pois ela terá mais qualidade e tecnologia suficiente para instalar apk em modo Android..
Assim seria mais fácil para vc e até irá melhorar os travamentos, pois as TVs não tem toda essa melhoria que um aparelho voltado somente para uma plataforma.

**Comment by Ramys** [comment]
Existem pessoas que trabalham com isso, eles cobram por quantidade.
1 ip é um valor  2 ips outro e por ai vai..
Se vc fizer o apk com limite para 5 pessoas, - quando uma sexta pessoal entrar no apk , acontecem os travamentos.
Geralmente por ip por mês gira em torno de 25 à 30 mensais.

**Comment by Brunowilliang** [comment]
entendi, e vc conseguira me fornecer essa lista?
uma para teste e depois eu pagaria assim que fizer funcionar certinho

**Comment by Ramys** [comment]
Essas listas eu já repassei para alguns amigos , e não está mais com 5 limites..
Provavelmente somente um ip livre..
Me passa um e-mail que eu te envio.

**Comment by Brunowilliang** [comment]
Tudo bem é para testes mesmo, meu email é brunowilliang@icloud.com

**Comment by Brunowilliang** [comment]
Oi @Ramys, deu certo enviar a lista?

**Comment by Ramys** [comment]
Opa..
Estou viajando , quando chegar eu te envio.

**Comment by Brunowilliang** [comment]
Oi @Ramys tudo bem? chegou de viagem?

**Comment by Brunowilliang** [comment]
@Ramys Oi Ramis, consegue me ajudar?

**Comment by Ramys** [comment]
Lista enviada.
Vlws!
