### ISSUE TITLE
Eu entro no WebTvPlayer e ele simplismente carrega e não abre.. Alguma forma de resolver isso? Já tentei com os dois links. E a reprodução Web entra, porem a reprodução da erro depois de uns 5 seg.

### ISSUE THREAD

**Issue by MukhSant** [Ramys/Iptv-Brasil-2023#67]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Ramys** [comment]
Atualizado!
