### ISSUE TITLE
O login pro http://cplayer.io/ não funciona mais.

### ISSUE THREAD

**Issue by Leon197575** [Ramys/Iptv-Brasil-2023#69]
O player é perfeito e melhor que já vi! Mas expirou o login. Há como renovar? Tem mais informações dele?

**Comment by renato-aguena** [comment]
Tem alguma forma de conseguir um usuário exclusivo que não fique com o Ao Vivo caindo e os filmes e series tenha que ficar tentando até funcionar?

**Comment by Demmramm** [comment]
Algumas lista ficaram offline. A que utilizo pfsv.m3u8, a clente.m3u8 e a CanaisB5. Abre no app IPTV mas não estão disponíveis os cananis.

**Comment by Demmramm** [comment]
Antes que esqueça vou fazer contribuições mensais no seu PIX, está ok aquele código?

**Comment by Ramys** [comment]
Atualizado!

**Comment by Ramys** [comment]
> Antes que esqueça vou fazer contribuições mensais no seu PIX, está ok aquele código?

Isso mesmo ;
Obrigado!
