### ISSUE TITLE
Listas .m3u8 ficaram offline.

### ISSUE THREAD

**Issue by Demmramm** [Ramys/Iptv-Brasil-2023#71]
Quando a lista online expirou, também expiraram as lista disponibilizadas no repositório, para uso com apps iptv, etc.
listas Pfsv, CanaisB5, Cliente, X90 etc. 
Como poderia ajudar a manter essas listas online?

**Comment by Ramys** [comment]
Boa noite. 
Irei atualizar todas as listas.

**Comment by Carlosmfcosta** [comment]
Qtos acessos simultaneos pode ser feito.  Tem alguma limitação

**Comment by Ramys** [comment]
Depende da lista ..
A maioria é para 1 ou até 5 ips..
Já adicionei lista com até 800 conexões.
