### ISSUE TITLE
O site http://cplayer.io/ também funciona como aplicativo?

### ISSUE THREAD

**Issue by Modanes** [Ramys/Iptv-Brasil-2023#72]

**Comment by Ramys** [comment]
Se vc abrir na tv via navegador , sim.
Porém o Aplicativo é mais eficaz .

**Comment by Modanes** [comment]
E qual aplicativo é?

**Comment by Ramys** [comment]
Esse .
https://mega.nz/file/Altl2YYZ#99-FgcdvzCim6Pkw5JcqhwEqFb8WrFI7y41Q-gk5EJs

Porém é somente para Android.

**Comment by Modanes** [comment]
Fechou, muito obrigado :)
