### ISSUE TITLE
Login e Senha Inválido no WEB Player

### ISSUE THREAD

**Issue by G4BRII3L** [Ramys/Iptv-Brasil-2023#73]
O login: 378724 e a senha: pcapQ5 estão inválidos no web player: http://cplayer.io/

**Comment by BRUCKAO** [comment]
Realmente parou

**Comment by Ramys** [comment]
Está em manutenção o provedor.

**Comment by BRUCKAO** [comment]
> Está em manutenção o provedor.

Qual o endereço mesmo para usar no IPTV Smarters Pro ?

**Comment by Ramys** [comment]
Servidor Online novamente!
