### ISSUE TITLE
iptvsmarters funciona?

### ISSUE THREAD

**Issue by ramonenghaw** [Ramys/Iptv-Brasil-2023#75]
Olá! Primeiramente obrigado por seu trabalho!

A duvida é em relação ao iptvsmarters, ele funciona? Pois na pagina inicial não tem o login e senha...

Com relação ao IPTV ACSC, existe algum app para a WEBOS da LG que eu possa acessar esta lista caso o iptvsmarters não funcione ao invés de precisar logar pelo navegador web.

Mais uma vez obrigado!

**Comment by Ramys** [comment]
Vc pode usar o login da club  que postei no início.
Sobre a tv , eu indico que compre uma tv box e instale o apk nela , pois a tv box tem mais suporte e é indicado para aplicativos.
Para rodar direto na tv não funciona muito bem... Trava de mais e não tem tanto suporte.

**Comment by Ramys** [comment]
Login: 378724

senha: pcapQ5

url: http://bdtb.io:80

**Comment by ramonenghaw** [comment]
Obrigado! Deu certo no iptv smarters! Não está mais travando! A dúvida é se tem como eu excluir os canais adultos pra que nem apareça a categoria na lista, pois só consegui limitar com a criação da senha.

**Comment by Ramys** [comment]
Pelo o aplicativo que linkei para download, na opção Controle dos pais , dá para bloquear as listas e elas ficam offline.

**Comment by ramonenghaw** [comment]
Mais existe um problema, no IPTV Smarters está funcionando perfeitamente, não está travando, o problema é que ele mostra uma categoria chamada "Adicionados recentemente", que seriam os canais adicionados recentemente, e tem muito conteúdo adulto, mesmo criando a senha, ele fica exibindo, o controle dos pais só bloqueia a lista na categoria adulta.

**Comment by Ramys** [comment]
Então..
Para não aparecer isso lá, vc não pode assistir , né kkk

**Comment by ramonenghaw** [comment]
Não entendi kkkk eu excluir o app, configurei a lista novamente, mas mesmo assim o smarters itv mostra essa categoria que tá misturado conteúdo adulto com não adulto, sacou? Eu acredito que seja algo específico desse app, no web player mesmo não tem essa categoria de adicionados recentemente... eu vou testar com outro app, essa config que vc mandou, posso usar em outro app tbm?

**Comment by Ramys** [comment]
Se pedir url , pode sim.
