### ISSUE TITLE
Usuario e senha iptvsmarters.com

### ISSUE THREAD

**Issue by DARVISSONL** [Ramys/Iptv-Brasil-2023#76]
Qual usuario e senha eu uso para configurar o iptvsmarters.com, porque na descrição só tem isso 

Qualquer Lista poderá ser adicionada no painel iptvsmarters.

Qualquer nome:

Login:

senha:

url: http://api.magiaiptv.com/ url2: [http://api.magiaiptv.com:80](http://api.magiaiptv.com/)

**Comment by Ramys** [comment]
Pode usar a primeira..
Essa está offline

**Comment by Ramys** [comment]
Login: 378724

senha: pcapQ5

url: http://bdtb.io:80
