### ISSUE TITLE
é possivel utilizar essas listas IPTV com o Stremio?

### ISSUE THREAD

**Issue by Heus-Sueh** [Ramys/Iptv-Brasil-2023#77]
com esse addon talvez: https://stremio-addons.netlify.app/your-iptv

**Comment by Ramys** [comment]
Sim ..
É só adicionar esse link.
http://bdtb.io/get.php?username=378724&password=pcapQ5&type=m3u_plus&output=ts

**Comment by Heus-Sueh** [comment]
pode divulgar esse repositório? ou vc acha que aumenta chance de vc tomar **Direitos** **Autorais** por algum motivo ou removerem esse repositório?

**Comment by Ramys** [comment]
Como são links pescados eu tenho esse receio.
Eu uso umq ferramenta que pesca esses links via rede.
Só não partilho aqui o modo como faço pois, tenho medo de ser denunciado :)
Em breve irei criar um fórum privado com umas dicas e macetes de como criar sua própria lista com pesca .
