### ISSUE TITLE
Lista off-line 

### ISSUE THREAD

**Issue by tiagovieira075** [Ramys/Iptv-Brasil-2023#78]
Olá, acredito que a lista que você disponibilizou está com problemas, principalmente na parte de filmes e séries.
A TV ao vivo funciona porém os filmes e séries não. Desde já agradeço muito por ter disponibilizado isso pra gente, muito agradecido. <3

**Comment by Ramys** [comment]
Geralmente isso se dá por causa da manutenção deles , em breve estará funcionando normalmente.
