### ISSUE TITLE
Sistema Orsay Samsung, como configurar?

### ISSUE THREAD

**Issue by AdolfoPD** [Ramys/Iptv-Brasil-2023#83]
Ou funciona com alguns desses apps da foto![image](https://github.com/Ramys/Iptv-Brasil-2023/assets/37916286/01700435-4ec0-45e6-a8df-ffc4f01a2b9d)

**Comment by Ramys** [comment]
O duplexPlay é pago.
vc tem q adicionar via site dele as listas que tem no inicio do meu projeto.
Já o ottplayer é grátis ... mesma coisa faz uma conta no site deles e envia as listas para lá via url ou pasta.
Duplex é o melhor de todos que tem nessa lista.
