### ISSUE TITLE
AJUDA PARA CONECTAR A SMART TV

### ISSUE THREAD

**Issue by TOTINAGESTAO** [Ramys/Iptv-Brasil-2023#84]
Olá, primeiramente quero agradecer a este belo projeto que vc nos disponibiliza muito obrigado de verdade !

Queria saber qual o ip eu coloco no DNS da minha Smart TV para que eu conecte ao iptv por meio do Smart STB e Smart Up , pois quando tento entrar pelo webplayer fica em tela preta.

minha tv é Panasonic um pouco antiga, por isso queria saber o ip do dns para eu poder assistir na tv, agradeceria se pudesse me ajudar

**Comment by Ramys** [comment]
Tenta esses dns.
DNS 1 =   107.152.41.78

DNS 2  =  107.152.41.79

**Comment by TOTINAGESTAO** [comment]
Testei os dois DNS e não funcionou :( , queria tanto por pra funcionar na TV se ela ao menos pegasse o player web, mas é só por DNS msm, se tiver outros e puder mandar eu agradeceria demais

**Comment by Ramys** [comment]
Eu tenho em algum lugar os dns da club tv..
Vou fuçar aqui até achar.

**Comment by TOTINAGESTAO** [comment]
cara  agradeço dms pela ajuda de coração, mt grato

**Comment by Ramys** [comment]
Achei o DNS.
212.102.61.80

Testa ai agora.

**Comment by Ramys** [comment]
@TOTINAGESTAO

**Comment by TOTINAGESTAO** [comment]
FUNCIONOU MANOO, MUITO OBRIGADO PELA AJUDA, DEU RUIM NA KINHA PLACA DE VIDEO POR ISSO DEMOREI A REAPONDER, VALEU PELA AJUDA MANO!!
