### ISSUE TITLE
como faço para colocar a playlist no baytv? deverias ter um passo a passo...

### ISSUE THREAD

**Issue by douglvsz** [Ramys/Iptv-Brasil-2023#87]
**Descreva o bug**
Uma descrição clara e concisa do que é o bug.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Vá para '...'
2. Clique em '....'
3. Role para baixo até '....'
4. Veja o erro

**Comportamento esperado**
Uma descrição clara e concisa do que você esperava que acontecesse.

**Capturas de tela**
Se aplicável, adicione capturas de tela para ajudar a explicar seu problema.

**Desktop (por favor, preencha as seguintes informações):**
 - SO: [por exemplo iOS]
 - Navegador [por exemplo, cromo, safári]
 - Versão [por exemplo, 22]

**Smartphone (preencha as seguintes informações):**
 - Dispositivo: [por exemplo iPhone6]
 - SO: [por exemplo iOS8.1]
 - Navegador [por exemplo, navegador de ações, safári]
 - Versão [por exemplo, 22]

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by Ramys** [comment]
Aqui tem um video explicando.
https://youtu.be/9v1YI4RqQ10?si=rLtyascDdVSIRMtw

**Comment by douglvsz** [comment]
essa uma lista funcional? se nao, como faço para obter uma?

**Comment by Ramys** [comment]
Para você ter uma lista fixa somente para o seu ip , teria que entrar em contato com alguém que faça essa revenda..
Conheço um rapaz que trabalha para a club tv , creio que a lista custr uns 25 mensais.
Essa é a base dad listas iptv.
Esse programa ai ele é pago , vc tem q comprar a licença..
Eu , indico vc comprar uma tv box com mínimo de 4 ram e uns 16 de memória interna.
Assim vc não teria tantos problemas quanto um aplicativo direto na tv , até pq a tv não tem tanto suporte para o mesmo.
